version: "3.9"

services:
  base:
    image: "node:16"
    working_dir: "/app"
    volumes:
      - tujutuju-nodemodules:/app/node_modules
      - .:/app

  install:
    extends:
      service: base
    command: "npm install"

volumes:
  tujutuju-nodemodules:
    external: true
