version: "3.8"
services:
  api:
    container_name: "api"
    env_file: ".env"
    image: "tujutuju-api:latest"
    build:
      context: "."
      dockerfile: "Dockerfile"
    ports:
      - "${PORT}:${PORT}"
    # volumes:
    #   - "./volumes/api:/usr/src/app"
    depends_on:
      - db

  db:
    container_name: "db"
    env_file: ".env"
    image: "postgres:latest"
    volumes:
      - "./volumes/db:/var/lib/postgresql/data"
