CREATE USER docker WITH PASSWORD 'docker';
CREATE DATABASE docker;
GRANT ALL PRIVILEGES ON DATABASE docker TO docker;
GRANT ALL ON ALL TABLES IN SCHEMA public TO docker;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO docker;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA public TO docker;
