name: Deploy AWS EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: "aws-deploy"

jobs:
  deploy-aws:
    runs-on: ubuntu-latest
    steps:
      - name: Executing AWS SSH scripts
        uses: appleboy/ssh-action@master
        env:
          AWS_ENV_FILE: ${{ secrets.AWS_ENV_FILE }}
        with:
          host: ${{ secrets.AWS_EC2_SSH_HOST }}
          port: 22
          username: ${{ secrets.AWS_EC2_USER }}
          key: ${{ secrets.AWS_EC2_SSH_KEY }}
          timeout: "5m"
          envs: AWS_ENV_FILE
          script: |
            cd ~/tujutuju-api
            docker-compose down
            docker rmi $(docker images -f "dangling=true" -q)

            git pull origin main
            echo $AWS_ENV_FILE | base64 --decode > .env
            docker volume create tujutuju-nodemodules && docker-compose -f docker-compose.builder.yaml run --rm install && docker-compose up -d
